name: advanced workflow

on:
  workflow_dispatch:

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
    - name: firstJob script
      shell: bash
      run: echo Hello World! This is the first job
    - name: Checkout
      uses: actions/checkout@v6.0.1
    - name: Print to Log
      id: print-to-log
      uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: ${{ github.actor }}
    - name: time
      run: |
        echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time}}"
  secondJob:
    runs-on: ubuntu-latest
    steps:
    - name: secondJob Script
      shell: bash
      run: |
        echo this is the second job
        echo and this is a multi-line script  
  
